language: python

arch:
  - amd64
  - ppc64le

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

env:
  global:
    - COVERAGE_CMD="coverage run --append"

install:
  # install tox-travis explicitly after tox to avoid
  # pkg_resources.VersionConflict, see
  # https://travis-ci.org/scampersand/bienvenue/jobs/196462565
  # https://github.com/ryanhiebert/tox-travis/issues/26
  - pip install tox
  - pip install tox-travis
  - pip install codecov

script:
  - tox

after_script:
  - codecov
